-- MySQL Script generated by MySQL Workbench
-- 04/17/17 20:43:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema senior_project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `senior_project` ;

-- -----------------------------------------------------
-- Schema senior_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `senior_project` DEFAULT CHARACTER SET utf8 ;
USE `senior_project` ;

-- -----------------------------------------------------
-- Table `senior_project`.`tbl_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `senior_project`.`tbl_user` ;

CREATE TABLE IF NOT EXISTS `senior_project`.`tbl_user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `cover_photo` VARCHAR(200) NULL DEFAULT NULL,
  `tel_no` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `citizen` VARCHAR(3000) NULL DEFAULT NULL,
  `nationality` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `verify` INT(1) NULL DEFAULT NULL,
  `bank_account` VARCHAR(3000) NULL DEFAULT NULL,
  `criminal` VARCHAR(45) NULL DEFAULT NULL,
  `verify_bank` INT(1) NULL DEFAULT '0',
  `verify_citizen` INT(1) NULL DEFAULT '0',
  `verify_criminal` INT(1) NULL DEFAULT '0',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `usrename_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `senior_project`.`tbl_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `senior_project`.`tbl_activity` ;

CREATE TABLE IF NOT EXISTS `senior_project`.`tbl_activity` (
  `activity_id` INT(11) NOT NULL AUTO_INCREMENT,
  `activity_name` VARCHAR(100) NULL DEFAULT NULL,
  `activity_desc` VARCHAR(250) NULL DEFAULT NULL,
  `cover_photo` VARCHAR(200) NULL DEFAULT NULL,
  `province` VARCHAR(45) NULL DEFAULT NULL,
  `location` VARCHAR(45) NULL DEFAULT NULL,
  `owner` VARCHAR(100) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  `colorcode` VARCHAR(45) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`activity_id`),
  UNIQUE INDEX `activity_name_UNIQUE` (`activity_name` ASC),
  INDEX `owner_idx` (`owner` ASC),
  CONSTRAINT `owner`
    FOREIGN KEY (`owner`)
    REFERENCES `senior_project`.`tbl_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `senior_project`.`tbl_itinerary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `senior_project`.`tbl_itinerary` ;

CREATE TABLE IF NOT EXISTS `senior_project`.`tbl_itinerary` (
  `itinerary_id` INT(11) NOT NULL AUTO_INCREMENT,
  `activity_id` INT(11) NULL DEFAULT NULL,
  `times` VARCHAR(40) NULL DEFAULT NULL,
  `itinerary_desc` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`itinerary_id`),
  INDEX `FK_ITINERARY_idx` (`activity_id` ASC),
  CONSTRAINT `FK_ITINERARY`
    FOREIGN KEY (`activity_id`)
    REFERENCES `senior_project`.`tbl_activity` (`activity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `senior_project`.`tbl_operating_day`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `senior_project`.`tbl_operating_day` ;

CREATE TABLE IF NOT EXISTS `senior_project`.`tbl_operating_day` (
  `operating_id` INT(11) NOT NULL AUTO_INCREMENT,
  `day_of_week` VARCHAR(45) NULL DEFAULT NULL,
  `activity_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`operating_id`),
  INDEX `acitivity_id_idx` (`activity_id` ASC),
  CONSTRAINT `acitivity_id`
    FOREIGN KEY (`activity_id`)
    REFERENCES `senior_project`.`tbl_activity` (`activity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `senior_project`.`tbl_photo_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `senior_project`.`tbl_photo_activity` ;

CREATE TABLE IF NOT EXISTS `senior_project`.`tbl_photo_activity` (
  `photo_activity_id` INT(11) NOT NULL AUTO_INCREMENT,
  `photo_path` VARCHAR(3000) NULL DEFAULT NULL,
  `activity_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`photo_activity_id`),
  INDEX `FK_PHOTO_idx` (`activity_id` ASC),
  CONSTRAINT `FK_PHOTO`
    FOREIGN KEY (`activity_id`)
    REFERENCES `senior_project`.`tbl_activity` (`activity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `senior_project`.`tbl_tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `senior_project`.`tbl_tickets` ;

CREATE TABLE IF NOT EXISTS `senior_project`.`tbl_tickets` (
  `ticket_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ticket_name` VARCHAR(45) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `activity_id` INT(11) NULL DEFAULT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `activity_id_idx` (`activity_id` ASC),
  CONSTRAINT `activity_id`
    FOREIGN KEY (`activity_id`)
    REFERENCES `senior_project`.`tbl_activity` (`activity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
